[package]
name = "rust_os"
version = "0.1.0"
authors = ["Sullivan Myer <slucasmyer@icloud.com>"]
edition = "2021"

[dependencies]
bootloader = "0.9.23"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"